# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TravelPlanner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TravelPlanner
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore', '5.7.0'

 # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
