# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AppWooW' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppWooW
  pod 'FBSDKLoginKit'
  pod 'Firebase/Auth'
#  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

#  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end
